### ISSUE TITLE
Should not alter unload directly

### ISSUE THREAD

**Issue by chrilith** [marcj/css-element-queries#49]
Hi,

You should not alter onload directly as you do.
Please, first check that an window.onload is not already set before altering it. This may break client code.

Thanks!

**Comment by facboy** [comment]
I'm also having this problem.  Also, it appears that in the domLoaded() function you keep adding the handler in multiple ways even if you have successfully added the handler, ie if you have called addEventListener because you are on Chrome/Mozilla/Opera, why do you still need to override window.onLoad and/or check for Safari/Konquerer?

**Comment by marcj** [comment]
Indeed, let us fix that. Feel free to send a PR if you find a fix faster.

**Comment by marcj** [comment]
FIxed in latest version.
