### ISSUE TITLE
Confirm: allowed to call ElementQueries.init multiple times? 

### ISSUE THREAD

**Issue by gebrits** [marcj/css-element-queries#95]
Each time when new dom-elements are added dynamically I need to call ElementQueries.init. 
Is this supported? I.e.: no duplicate listeners on already existing elements, etc? 

Intuitively (naively?), from a performance standpoint it might make sense to just provide a collection of the newly added dom-elements to ElementQueries as a pruning filter to speed up performance. Is this supported, useful to add or not needed?

**Comment by marcj** [comment]
Yes you can call .init as often as you want. It only adds new not yet known elements to the tracked elements. I like the idea of limiting the `init` call to some known elements. The thing is, the tracker doesn't work that way. It doesn't start with an element but with the css. Limiting css rules based on elements is not yet possible since css rules need to be parsed anyway and once executed the current filter, by jumping over the elements it already knows, has the same performance impact. One thing that could improve performance is `Element.querySelectorall` (https://developer.mozilla.org/en/docs/Web/API/Element/querySelectorAll) which executes css rules that contain a element query statement (`[max-width~=...]`, ...) in the context of the given element that you definitely know has some changed sub elements.

Possible API: `ElementQueries.init(myComponent)`, and `init` is passing the `myComponent` from `findElementQueriesElements` to `getQuery(myComponent)` which returns then not a global `document. querySelectorAll` but a `myComponent.querySelectorAll` which should increase performance due to the fact that it does only need to check css rules again a sub set of DOM elements instead of all. Do you want to provide a Pull-Request? :)

**Comment by marcj** [comment]
This could also be the base for the integration in libraries like Angular or React (#81) where each Component could trigger a `ElementQueries.init(myComponent` when it detects that its DOM has been re-rendered. I'm only not yet sure if such events exist in those libraries.

**Comment by gebrits** [comment]
Cheers. 

> since css rules need to be parsed anyway and once executed the current filter, by jumping over the elements it already knows, has the same performance impact.

Does this mean parsing css is done on every call to `ElementQueries.init`? Feels like a caching opportunity here.

**Comment by marcj** [comment]
Not parsing (meaning reading all css files), but executing the cached css rules to get from `querySelectAll` all elements that apply.

**Comment by marcj** [comment]
Limiting the scope of `querySelectorAll` as described above could reduce cpu usage

**Comment by phil-lgr** [comment]
@marcj Angular 1.x directives' provide function that are called when DOM is ready to be manipulated (see https://docs.angularjs.org/api/ng/service/$compile#post-linking-function), I tried it and it works perfectly so far.. using your lib really changed the way I think about my layout when I build my components :) thx for that.

> Possible API: ElementQueries.init(myComponent), and init is passing the myComponent from findElementQueriesElements to getQuery(myComponent) which returns then not a global document. querySelectorAll but a myComponent.querySelectorAll which should increase performance due to the fact that it does only need to check css rules again a sub set of DOM elements instead of all. Do you want to provide a Pull-Request? :)

I'll look into this and the code and if I am confident, I'll comment again and work on the feature.

**Comment by kaljak** [comment]
I have currently performance issues when calling ElementQueries.init() every time the HTML is changed (takes up to 100ms).
As the CSS is only loaded once - the rules don't need to be read again - wouldn't it be possible to expose findElementQueriesElements() to ElementQueries so that only this function needs to be called after HTML is changed? (takes only about 20ms)

**Comment by marcj** [comment]
Yeah, sure. Feel free to send a pull request. The new public method ElementQueries.findElementQueriesElement(container = null) should get an optional container to limit to search to a subtree in the DOM.

**Comment by kaljak** [comment]
Any updates on this? :)

**Comment by filipemir** [comment]
I also would like to see support added for this. I have a library that loads on sites I don't control. I'm concerned someone may load my script (which uses ElementQueries) and also have either their own copy of ElementQueries or -- for some odd reason -- have elements defined with the attributes ElementQueries looks for (max-width, etc). To prevent my copy of ElementQueries from affecting elements I don't control, I need to somehow restrict its functionality to specific elements/components.

I'll try to throw up a PR when I have some time to carve out for this.
