### ISSUE TITLE
not working with windows resize 

### ISSUE THREAD

**Issue by nabukhas** [marcj/css-element-queries#96]
i can't get it working when attach event to a div with windows resize

**Comment by marcj** [comment]
What do you mean with 'with windows resize', 'attach event to a div', and what exactly means "can't get it working"? Also which versions, which browser?

**Comment by nabukhas** [comment]
Hi marcj,,,

sorry for not being clear 

i'm attaching ResizeSensor to a DIV, i need this div to be re-sized based on window re-sized 
Using Google Chrome Version 48.0.2564.116 m
ResizeSensor Version 0.3.2

**Comment by marcj** [comment]
Can you please create a fiddle somewhere (like in jsfiddle.net)? if you need to attach to window's resize element, then you should do so using `window.addEventListener('resize', function(){})` instead of using ResizeSensor. The Sensor only calls the listener when the DIV itself changes its dimensions. If you resize the window and the div doesn't change its dimensions, nothing is called.

**Comment by nabukhas** [comment]
Thank you marcj,

i used the window re-size event and catch the div dimension 
and this solved my problem
