### ISSUE TITLE
Problems on IE11 due to Error object discrepancies

### ISSUE THREAD

**Issue by jpfranco** [marcj/css-element-queries#98]
Hey guys, so I ran into an issue while testing the latest version on IE11. An error is thrown, and the element queries are not applied. I've pretty much narrowed it down to this part of the code:

```
for (var i = 0, j = document.styleSheets.length; i < j; i++) {
                try {
                    readRules(document.styleSheets[i].cssRules || document.styleSheets[i].rules || document.styleSheets[i].cssText);
                } catch(e) {
                    if (e.name !== 'SecurityError') {
                        throw e;
                    }
                }
            }
```

If I understand correctly, this is meant to skip any protected browser stylesheets that aren't available to the client (or something along those lines), but it seems that on IE11 the error that is thrown when attempting to access restricted stylesheets has a generic name of `Error` instead of `SecurityError`. The error's message is `Access is denied.` though. If I comment out the `throw` line the element queries are applied correctly.

It seems that even if the error wasn't security related, silently skipping the offending stylesheet would have no adverse effects on the rest of the code, so maybe it would be possible to log a warning instead of throwing the error? Thanks

**Comment by marcj** [comment]
Oh I see, maybe it's then the best to just hide all errors while accessing the styleSheets elements or we should check additionally for `'Access is denied' in e.message`

**Comment by thisYogesh** [comment]
Hi @marcj ,
I want know that how much resize sensor logic (trick) will sustainable to maintain its functionality on farther releases of browsers?

As I gone through its js code its pretty impressing and amazing that scroll event is able to fire after changes the size of any element (except stand alone tags... Obviously! we need wrapper on it). 

My concern is that what if this behavior of scroll event is consider as a bug and in latest releases of any browser this got resolved then what!!

Because its time to implement this code in the big product so I have to be very careful.....
As of now we are using **setTimeout** to achieve this kind of functionality.

Kindly please reply on this!...

_Regards,
Yogesh Jagdale_

**Comment by kaljak** [comment]
I have the same problem in our testing environment. In my opinion the errors should be hidden. Should I make a PR?

**Comment by marcj** [comment]
Fixed in upcoming version.
